### ISSUE TITLE
2024.8 breaks dashboard in app

### ISSUE THREAD

**Issue by Bcukier** [wassy92x/lovelace-ha-dashboard#18]
With the new update, the sidebar / dashboard doesn’t behave well when displayed in the app.  It displays perfectly in the browser, but when in the app I see this:

![IMG_0341](https://github.com/user-attachments/assets/260fca6f-405e-488f-b71e-e93dcbb092bc)

in the browser it displays this (which is correct):

![IMG_0342](https://github.com/user-attachments/assets/9ec4b72b-6cc4-4664-91bf-8eab5c55c760)

Any help would be appreciated.

**Comment by wassy92x** [comment]
I habe some questions regarding your issue.
Is the first screenschot taken from the original Home Assistant App?
What's the version of the app?
What device do you use?

**Comment by Bcukier** [comment]
The first picture is from the HA app on iOS.  HA companion app 2024.8 on an ipad (both mini and full ipad).

Let me know if you need any other info.

**Comment by Bcukier** [comment]
Any insight here?  I can also post the issue on the HA forums, but I have traced it back to the dashboard integration, and only on the app.  (The same cards display perfectly in a vertical stack.  I just really like the aesthetic that this integration provides for the tablet displays).

**Comment by Bcukier** [comment]
It is now working again. 2024.8.3 seems to have resolved it!
