### ISSUE TITLE
Horizontal layout for view

### ISSUE THREAD

**Issue by areyoufserious** [wassy92x/lovelace-ha-dashboard#3]
Sidebar requires 'custom:ha-dashboard' setting
Is there any way to activate sidebar but set my layout type of my layout horizontal ?

**Comment by wassy92x** [comment]
You can use every card inside my dashboard. So if your horizontal layout is a card you can add it as a card. If this card should fill the complete space, you have to set  "usePanel" to true.

**Comment by ant-ms** [comment]
I would support getting this as well. Horizontal cards can work, but are a pain to deal with (especially when you want your dashboard to also work on mobile).

**Comment by wassy92x** [comment]
Could you please provide me some more information. What is your intention / idea? Maybe you can provide a small mockup/ drawing  or something like that.

**Comment by areyoufserious** [comment]
> You can use every card inside my dashboard. So if your horizontal layout is a card you can add it as a card. If this card should fill the complete space, you have to set "usePanel" to true.

thanks i will try
