### ISSUE TITLE
HADashboard already exist for 6 years.

### ISSUE THREAD

**Issue by ReneTode** [wassy92x/lovelace-ha-dashboard#4]
for those people who are searching for the real HAdashboard (which is part of Appdaemon) just go to 
https://appdaemon.readthedocs.io/en/latest/index.html

or install the Appdaemon addon.

it would be nice if this project would get a different name.

**Comment by wassy92x** [comment]
Do you have some naming suggestions?

**Comment by ReneTode** [comment]
custom HA frontend?
my HA frontend?
from the pics i see its more a frontend then a dashboard.
you could also go for any name that isnt a description.
like: mydab, wasdab, dab92, or something like that, and place in the description what it is.
