### ISSUE TITLE
Backgroud color

### ISSUE THREAD

**Issue by w1tw0lf** [wassy92x/lovelace-ha-dashboard#5]
Trying to change the background color.

Tried with `--sidebar-background` and `background` without any success. Can you perhaps share how to ?

**Comment by berndoranje** [comment]
I also would really like to see how to implement the --sidebar..... options. Where and how do you add the css styling options?

**Comment by wassy92x** [comment]
You have to set those variables inside a custom theme. Please refer the following home assistant documentation: https://www.home-assistant.io/integrations/frontend/
