### ISSUE TITLE
setting css variables

### ISSUE THREAD

**Issue by ghost** [wassy92x/lovelace-ha-dashboard#9]
Hi,

I have created theme.  The yaml is:

hadash:
  --sidebar-min-width: 200
  --sidebar-max-width: 200

...but this doesn't seem to have any effect.  What am I dong wrong?

**Comment by wassy92x** [comment]
Have you selected the new theme in your Home Assistant settings?

**Comment by ghost** [comment]
yes.

`theme: hadash` at the same level as (and just after) `view:`

**Comment by ghost** [comment]
OK, worked it out.  The yaml should have been:

```
hadash:
  sidebar-min-width: 200
  sidebar-max-width: 200
```

...with no leading "--".
